name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        cache: 'npm'

    - run: npm ci
    - run: npm run build
    - run: npm test
