name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci
      working-directory: ${{ env.BUILD_PATH }}

    - name: Build site
      run: npm run build
      working-directory: ${{ env.BUILD_PATH }}

    - name: Test site
      run: npm test
      working-directory: ${{ env.BUILD_PATH }}
